name: Generate Profile Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: nateboy318
          BRANCH_NAME: output
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          UTC_OFFSET: -5
